.base: &base
  port: 22
  config_file: ~/.ssh/config
  identity_file: ~/.ssh/id_rsa
  forward_agent: true
  multiplexing: true
  ssh_multiplexing: true
  ssh_type: native
  stage: production
  roles:
    - app
#    - db
  deploy_path: ~/app

www.callone.de:
  <<: *base
  stage: production
  branch: master
  
w015529a.kasserver.com:
  <<: *base
  hostname: w015529a.kasserver.com
  user: ssh-w018ea0a
  deploy_path: '/www/htdocs/w018ea0a/callone-staging'
  stage: staging
  branch: staging
